# Generated by Django 5.0.6 on 2024-08-19 03:30

import api.models.shelter_user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('user_type', models.CharField(default='null', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShelterUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estado', models.CharField(blank=True, max_length=128, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True, validators=[api.models.shelter_user.validate_postal_code])),
            ],
            options={
                'verbose_name': 'Shelter User',
                'verbose_name_plural': 'Shelter Users',
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='DogPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds', models.CharField(max_length=255)),
                ('image', models.ImageField(default='temp_image.jpg', upload_to='dog_images/')),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('tieneCollar', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('edad', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=255)),
                ('caracteristicas', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True)),
                ('form_type', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogPredictionShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds', models.CharField(max_length=255)),
                ('image', models.ImageField(default='temp_image.jpg', upload_to='dog_images/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('edad', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=255)),
                ('caracteristicas', models.TextField(blank=True)),
                ('sexo', models.CharField(blank=True, max_length=50)),
                ('tamanio', models.CharField(blank=True, max_length=50)),
                ('temperamento', models.CharField(blank=True, max_length=100)),
                ('vacunas', models.CharField(blank=True, max_length=255)),
                ('esterilizado', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shelteruser')),
            ],
        ),
    ]
