# Generated by Django 5.0.6 on 2024-07-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds', models.CharField(max_length=255)),
                ('image', models.ImageField(default='temp_image.jpg', upload_to='dog_images/')),
                ('estatus', models.CharField(default='Pendiente', max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('tieneCollar', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('edad', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=255)),
                ('caracteristicas', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True)),
                ('form_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShelterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono_shelter', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='shelters/')),
                ('publicaciones', models.ManyToManyField(blank=True, related_name='shelter_publicaciones', to='api.dogprediction')),
            ],
        ),
        migrations.CreateModel(
            name='EventAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_evento', models.CharField(max_length=255)),
                ('motivo_evento', models.CharField(max_length=255)),
                ('anfitrion_evento', models.CharField(max_length=255)),
                ('fecha_evento', models.DateField()),
                ('marca_publicidad', models.CharField(max_length=255)),
                ('promocion_publicidad', models.TextField()),
                ('caracteristicas_publicidad', models.TextField()),
                ('image', models.ImageField(upload_to='Eventos/')),
                ('refUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.shelteruser')),
            ],
        ),
        migrations.AddField(
            model_name='dogprediction',
            name='Refugio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shelteruser'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('telefono_user', models.CharField(max_length=255)),
                ('publicaciones', models.ManyToManyField(blank=True, related_name='propietario', to='api.dogprediction')),
            ],
        ),
        migrations.AddField(
            model_name='dogprediction',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
