# Generated by Django 4.2.13 on 2024-09-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelteruser",
            name="descripcion",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
