# Generated by Django 4.2.13 on 2024-09-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAdvertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=255)),
                ("descripcion_evento", models.CharField(max_length=255)),
                ("lugar_evento", models.CharField(max_length=255)),
                ("motivo", models.CharField(max_length=255)),
                ("anfitrion_evento", models.CharField(max_length=255)),
                ("fecha_evento", models.DateField()),
                ("hora_evento", models.TimeField()),
                (
                    "refUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.shelteruser",
                    ),
                ),
            ],
        ),
    ]
