# Generated by Django 5.0.6 on 2024-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogprediction",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="dogprediction",
            name="ciudad",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dogprediction",
            name="direccion",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dogprediction",
            name="estado",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="dogprediction",
            name="edad",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="dogpredictionshelter",
            name="edad",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
