# Generated by Django 5.0.6 on 2024-08-07 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shelteruser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprediction',
            name='shelter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_predictions', to='api.shelteruser'),
        ),
        migrations.AddField(
            model_name='dogprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_predictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
