# Generated by Django 5.0.6 on 2024-09-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdogrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marked_dogs',
        ),
    ]
