# Generated by Django 4.2.13 on 2024-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_eventadvertisement_imagen_evento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventadvertisement",
            name="imagen_evento",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
