# Generated by Django 4.2.13 on 2024-09-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_shelteruser_cuenta_shelteruser_nombre_refugio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelteruser",
            name="nombre_refugio",
        ),
        migrations.RemoveField(
            model_name="shelteruser",
            name="telefono_refugio",
        ),
        migrations.AlterField(
            model_name="shelteruser",
            name="cuenta",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
