# Generated by Django 5.0.6 on 2024-08-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dogprediction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogPredictionShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds', models.CharField(max_length=255)),
                ('image', models.ImageField(default='temp_image.jpg', upload_to='dog_images/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('edad', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=255)),
                ('caracteristicas', models.TextField(blank=True)),
                ('sexo', models.CharField(blank=True, max_length=50)),
                ('tamanio', models.CharField(blank=True, max_length=50)),
                ('temperamento', models.CharField(blank=True, max_length=100)),
                ('vacunas', models.CharField(blank=True, max_length=10)),
                ('esterilizado', models.CharField(blank=True, max_length=10)),
                ('shelter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shelteruser')),
            ],
        ),
    ]
