# Generated by Django 4.2.13 on 2024-09-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_shelteruser_nombre_refugio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelteruser",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="users_images/"),
        ),
        migrations.AddField(
            model_name="shelteruser",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="users_images/"),
        ),
        migrations.AddField(
            model_name="shelteruser",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="users_images/"),
        ),
    ]
