# Generated by Django 5.0.6 on 2024-08-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dogpredictionshelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelteruser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
