# Generated by Django 5.0.6 on 2024-09-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_user_marked_dogs"),
        ("api", "0005_shelteruser_image1_shelteruser_image2_and_more"),
    ]

    operations = []
