# Generated by Django 5.0.6 on 2024-09-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_merge_20240927_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogprediction",
            name="edad",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="dogpredictionshelter",
            name="edad",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
