# Generated by Django 5.0.6 on 2024-08-16 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shelteruser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelteruser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
