# Generated by Django 4.2.13 on 2024-09-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_eventadvertisement_imagen_evento"),
        ("api", "0006_merge_20240927_1336"),
    ]

    operations = []
