# Generated by Django 5.0.6 on 2024-09-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_dogprediction_edad_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogprediction",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="dogprediction",
            name="ciudad",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dogprediction",
            name="direccion",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dogprediction",
            name="estado",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
