# Generated by Django 5.0.6 on 2024-08-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shelteruser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelteruser',
            name='user',
        ),
    ]
