# Generated by Django 5.0.6 on 2024-08-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_shelteruser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogprediction',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='dogprediction',
            name='shelter_user',
        ),
        migrations.AlterField(
            model_name='dogpredictionshelter',
            name='vacunas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
