# Generated by Django 5.0.6 on 2024-08-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_dogprediction_estatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogpredictionshelter',
            old_name='shelter_user',
            new_name='user',
        ),
    ]
