# Generated by Django 5.0.6 on 2024-08-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_shelter_user_dogpredictionshelter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelteruser',
            name='user_type',
            field=models.CharField(default='shelter', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
