# Generated by Django 5.0.6 on 2024-08-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shelteruser_user_type_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelteruser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
